type User {
  _id: ID!
  username: String!
}

type Query {
  me: User!
  isLogin: Boolean!
}

input NewUserInput {
  username: String!
  password: String!
  confirmPassword: String!
}

input loginUserInput {
  username: String!
  password: String!
}

input logoutUserInput {
  username: String!
}

input UpdateUsernameInput {
  username: String!
  password: String!
}

input UpdatePasswordInput {
  password: String!
  newPassword: String!
  confirmPassword: String!
}

type Mutation {
  signup(input: NewUserInput!): User!
  login(input: loginUserInput!): User!
  logout: User!
  updateUsername(input: UpdateUsernameInput!): User!
  updatePassword(input: UpdatePasswordInput!): User!
}