type User {
  _id: ID!
  username: String!
}

type Query {
  me: User!
  isLogin: Boolean!
}

input NewUserInput {
  username: String!
  password: String!
}

input UpdateUserInput {
  username: String!
  password: String!
}

type Mutation {
  signup(input: NewUserInput!): User!
  login(input: NewUserInput!): User!
  updateMe(input: UpdateUserInput!): User!
}